name: Push to All Lovable Repos

on:
  push:
    branches: [ "main" ]
    if: "github.event.head_commit.author.email != 'actions@github.com'"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          # Full clone to avoid missing objects
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Enable Git debugging
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1

      - name: Push to All Lovable Repos
        env:
          REPO_URLS: |
            https://github.com/irugoo/traveler-connect-hub.git
            https://github.com/irugoo/traveler-connect-hub-04.git
            https://github.com/irugoo/test1.git
        run: |
          for REPO_URL in $REPO_URLS; do
            echo "Pushing to $REPO_URL..."
            git remote add target "$REPO_URL"
            for i in {1..5}; do
              echo "Attempt $i..."
              git push target main:main --force && break || sleep 10
            done
            git remote remove target
            sleep 5
          done
