name: Push to All Lovable Repos

on:
  push:
    branches: [ "main" ]
    if: "github.event.head_commit.author.email != 'actions@github.com'"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Central Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0  # Full clone

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to All Lovable Repos
        env:
          REPO_URLS: |
            https://github.com/irugoo/traveler-connect-hub.git
            https://github.com/irugoo/traveler-connect-hub-04.git
            https://github.com/irugoo/test1.git
            https://github.com/irugoo/irugootravel1.git
        run: |
          for REPO_URL in $REPO_URLS; do
            echo "Syncing to $REPO_URL..."
            git remote add target "$REPO_URL"
            # Use token for authentication
            git push "https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/${REPO_URL#https://github.com/}" main:main --force
            git remote remove target
            sleep 5
          done
